version: '3'
services:
  solr:
    image: solr:7
    container_name: 'solr7'
    ports:
      - "18983:8983"
    volumes:
      - solr7-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  solr7-data:
    driver: local