version: '3'
services:
  solr:
    image: solr:7
    container_name: 'solr7'
    ports:
      - "18983:8983"
    volumes:
      - ./docker/solr:/opt/solr/setup
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
      - /opt/solr/setup
volumes:
  solr7-data:
    driver: local